### ISSUE TITLE
Checklist para Produção

### ISSUE THREAD

**Issue by cv** [servicosgovbr/portal-de-servicos#318]
## Em `app1` (`10.17.0.4`)

- [x] Incluir o hostname da máquina no `/etc/hosts`
- [x] Sobrescrever `/etc/sysconfig/guia-de-servicos-overrides` com o arquivo em `secrets/guia-de-servicos.producao.config` (ou o equivalente, enviado por email)
- [x] Limpar os índices do ElasticSearch:
```bash
app1~$ curl -XDELETE 'http://10.17.0.6:9200/gds-importador'
app1~$ curl -XDELETE 'http://10.17.0.7:9200/gds-importador'
```
- [x] Rodar o script `app-node-update`:

```bash
app1~$ wget https://raw.githubusercontent.com/servicosgovbr/guia-de-servicos/master/scripts/prod-like/app-node-update
app1~$ chmod +x app-node-update
app1~$ sudo ./app-node-update
```
- [x] Verificar que a propriedade `build` é a versão esperada:
```bash
app1~$ curl localhost:8080/info
```
```json
{
  "build": "1201",
  "time": "2015-05-21 19:14",
  "git": {
    "branch": "master",
    "commit": {
      "id": "1b37941",
      "time": "2015-05-21 18:59"
    }
  }
}
```
- [x] Verificar que a saúde do cluster está `UP`:
```bash
app1~$ curl localhost:8080/health
```
```json
{
  "status": "UP",
  "guiaDeServicosIndex": {
    "status": "UP",
    "gds-importador": "ok (638 docs)",
    "gds-persistente": "ok (4 docs)"
  },
  "elasticSearch": {
    "status": "GREEN",
    "nodes": 2,
    "node-0": "Dromedan",
    "node-1": "Arides"
  },
  "diskSpace": {
    "status": "UP",
    "free": 1781682176,
    "threshold": 10485760
  }
}
```

## Em `app2` (`10.17.0.5`)

- [x] Incluir o hostname da máquina no `/etc/hosts`
- [x] Sobrescrever `/etc/sysconfig/guia-de-servicos-overrides` com o arquivo em `secrets/guia-de-servicos.producao.config` (ou o equivalente, enviado por email)
- [x] Rodar o script `app-node-update`:

```bash
app2~$ wget https://raw.githubusercontent.com/servicosgovbr/guia-de-servicos/master/scripts/prod-like/app-node-update
app2~$ chmod +x app-node-update
app2~$ sudo ./app-node-update
```
- [x] Verificar que a propriedade `build` é a versão esperada:
```bash
app2~$ curl localhost:8080/info
```
```json
{
  "build": "1201",
  "time": "2015-05-21 19:14",
  "git": {
    "branch": "master",
    "commit": {
      "id": "1b37941",
      "time": "2015-05-21 18:59"
    }
  }
}
```
- [x] Verificar que a saúde do cluster está `UP`:
```bash
app2~$ curl localhost:8080/health
```
```json
{
  "status": "UP",
  "guiaDeServicosIndex": {
    "status": "UP",
    "gds-importador": "ok (638 docs)",
    "gds-persistente": "ok (0 docs)"
  },
  "elasticSearch": {
    "status": "GREEN",
    "nodes": 2,
    "node-0": "Dromedan",
    "node-1": "Arides"
  },
  "diskSpace": {
    "status": "UP",
    "free": 1781682176,
    "threshold": 10485760
  }
}
```

## No balanceador de carga (`10.17.0.3`):

- [x] Verificar que todos os servidores de aplicação estão visíveis (em verde) no `/lb-stats`
- [x] Abrir página principal e verificar que lista de categorias (menu lateral) possui 15 elementos
- [x] Verificar que o conteúdo de `/robots.txt` aponta para o `sitemap.xml`:
```bash
lb~$ curl -s 10.17.0.3/robots.txt
```
```
Sitemap: http://10.17.0.3/sitemap.xml

User-agent: *
Disallow:
```
- [x] Verificar que o código-fonte da página possui o site ID do Piwik correto:
```bash
lb~$ curl -s 10.17.0.3 | grep 'var siteId'
```
```javascript
    var siteId = '2';
```

**Comment by cv** [comment]
@bandarrinha confirma que essa checklist funcionou bem? Alguma crítica ou informação que seria útil?
